name: video-reprocessor
base: core22
version: '0.5.8'
summary: Video Reprocessor
description: |
  A GUI tool to reprocess videos using FFmpeg with various filters and modifiers.
  Built with Tauri, React, and Rust.

grade: stable
confinement: strict

apps:
  video-reprocessor:
    command: bin/video_reprocessor
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - opengl

parts:
  app:
    plugin: dump
    source: .
    build-packages:
      - libwebkit2gtk-4.1-dev
      - libssl-dev
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - pkg-config
      - curl
      - ca-certificates
      - wget
      - tar
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libssl3
      - libgtk-3-0
      - libayatana-appindicator3-1
      - librsvg2-2
      - ffmpeg
    override-build: |
      # Install Rust
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source "$HOME/.cargo/env"
      
      # Install Node.js manually
      NODE_VERSION=v20.11.0
      NODE_DISTRO=linux-x64
      wget https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-$NODE_DISTRO.tar.xz
      tar -xJvf node-$NODE_VERSION-$NODE_DISTRO.tar.xz
      export PATH=$PWD/node-$NODE_VERSION-$NODE_DISTRO/bin:$PATH
      
      npm install
      npm run build
      
      cd src-tauri
      cargo build --release
      cd ..
      
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp src-tauri/target/release/video_reprocessor $SNAPCRAFT_PART_INSTALL/bin/
